### ISSUE TITLE
It's seems that can not process not-ascii characters

### ISSUE THREAD

**Issue by chaoyebugao** [ghost1face/base62#1]
Such as love爱, this result has different result with https://base62.io/

**Comment by ghost1face** [comment]
Thanks for pointing this out, it looks like I've made a bad assumption on characters and handled characters as if encoding would only be ASCII.

I'm working on updating the library and tests to ensure no breakage.  Will update shortly.

**Comment by ghost1face** [comment]
Updates made and latest version uploaded to NuGet, it should be available very soon.  Thanks again for pointing out the lack of support for non-ascii characters.
