### ISSUE TITLE
Decoded byte[] is shorter than input byte[] with leading 0-bytes

### ISSUE THREAD

**Issue by boennhoff** [ghost1face/base62#4]
The actual problem is this: if the encoded byte[] has leading null-bytes (zero), then these are cut off by this algorithm. So the resulting byte[] is shorter than the input!

In this implementation this is masked by the fact that only the methods using strings as input are public (and strings don't normally contain the 0-byte)

**Comment by Place1** [comment]
The changed introduced to fix this issue causes an index out of bounds exception for a byte[] consisting of only null bytes.

I'm using the library to encode a zero-value GUID which is a 16-byte value where all bytes are 0.
